name: Bug Report

title: Title of the issue

description: Report an issue with firefox theme. Make sure to read installation instructions.

labels: ["bug"]

assignees:
  - datguypiko

body:

- type: dropdown
  attributes:
    label: System OS
    description: Select operating system you are having issue with. Not tested on MacOS, may still check the issue.
    options:
      - Windows
      - Linux
      - MacOS (Not tested)
      - Other
  validations:
    required: true

- type: checkboxes
  attributes:
    label: Select Firefox Build
    description: |
      Select the branch of firefox you reproduce the issue with. Theme code is based on Stable version.  
      `Stable`  - Full support.  
      `Beta`    - May suggest for a manual fix or not.  
      `Nightly` - May suggest for a manual fix or not.  
      `Dev`     - Not Tested.  
      `ESR`     - Not Tested, Try using older theme files.
    options:
       - label: Firefox Stable
       - label: Firefox Beta
       - label: Firefox Nightly
  validations:
    required: true

- type: input
  attributes:
    label: Firefox Version (Not required)
    placeholder: e.g. v140.0.1
  validations:
    required: false

- type: textarea
  attributes:
    label: Describe Your Issue
    description: Issue / Expected behavior / Add picture/video previews
    placeholder: Report the issue..
  validations:
    required: true

- type: textarea
  attributes:
    label: Add picture of your `Chrome` folder to see What `Extra Mods` and the correct file structure you are using.
    placeholder: Copy paste or attach files..
  validations:
    required: true

    - type: Dropdown
  attributes:
    label: Any 3rd party modification to OS?
    description: Do you use any 3rd party modifications that could affect window 
    options:
      - Yes
      - No
      - "I don't know"
  validations:
    required: false

    - type: markdown
  attributes:
    value: |
      Make sure that any 3rd party operating system modifications  
      you’re using aren’t negatively affecting the Firefox window: micaForEveryone, DWMBlurGlass, startallback  
      or custom linux themes.
